[General]
panelStyle=4
minimumIconSize=48
maximumIconSize=96
spacingFactor=0.5
floatingMargin=8
zoomingAnimationSpeed=16
bouncingLauncherIcon=true
showTooltip=true
tooltipFontSize=14
backgroundColorMetal2D=#ff0b1018
borderColorMetal2D=#2a3852
activeIndicatorColorMetal2D=#2f6fed
inactiveIndicatorColorMetal2D=#8b98ad
firstRunMultiScreen=false
firstRunWindowCountIndicator=false
