[General]
position=1
visibility=3
screen=0
showApplicationMenu=false
showPager=false
showTaskManager=true
showTrash=false
showWifiManager=false
showVolumeControl=false
showBatteryIndicator=false
showKeyboardLayout=false
showVersionChecker=false
showClock=false
launchers=com.mitchellh.ghostty;org.mozilla.firefox
