#!/usr/bin/env python3
"""Draws the square GOBLINCAKES frames for the Plasma theme.

Plasma draws text fields, buttons, highlights and tooltips (also inside AppGrid and
every popup) from SVGs in the theme. Breeze's have rounded corners and glows; these
are flat, square and in the palette. Run from the repo root:

    python3 tools/plasma-frames.py
"""
from pathlib import Path

THEME = Path("files/system/usr/share/plasma/desktoptheme/goblincakes")

# Palette (see CLAUDE.md)
NIGHT = "#0E1420"
DEEP = "#12203A"
ACCENT = "#2F6FED"
BORDER = "#1E2A40"
PANEL_BORDER = "#2A3852"
SUBTLE = "#1A2438"

NONE = "none"


def frame(prefix, y, border, fill, width=1, margin=6, border_opacity=1.0, fill_opacity=1.0):
    """One square 9-piece frame (100×100) at row y, plus its margin hints."""
    p = f"{prefix}-" if prefix else ""
    b, size = width, 100
    inner = size - 2 * b
    bo = f' fill-opacity="{border_opacity}"' if border_opacity != 1.0 else ""
    fo = f' fill-opacity="{fill_opacity}"' if fill_opacity != 1.0 else ""
    out = [f"  <!-- {prefix or 'frame'} -->"]
    pieces = {
        "topleft": (0, 0, b, b), "top": (b, 0, inner, b), "topright": (size - b, 0, b, b),
        "left": (0, b, b, inner), "right": (size - b, b, b, inner),
        "bottomleft": (0, size - b, b, b), "bottom": (b, size - b, inner, b),
        "bottomright": (size - b, size - b, b, b),
    }
    for name, (x, yy, w, h) in pieces.items():
        out.append(f'  <rect id="{p}{name}" x="{x}" y="{y + yy}" width="{w}" height="{h}" fill="{border}"{bo}/>')
    out.append(f'  <rect id="{p}center" x="{b}" y="{y + b}" width="{inner}" height="{inner}" fill="{fill}"{fo}/>')
    # Inner padding
    out.append(f'  <rect id="{p}hint-top-margin" x="110" y="{y}" width="1" height="{margin}" fill="none"/>')
    out.append(f'  <rect id="{p}hint-bottom-margin" x="115" y="{y}" width="1" height="{margin}" fill="none"/>')
    out.append(f'  <rect id="{p}hint-left-margin" x="110" y="{y + 20}" width="{margin}" height="1" fill="none"/>')
    out.append(f'  <rect id="{p}hint-right-margin" x="110" y="{y + 30}" width="{margin}" height="1" fill="none"/>')
    return out


def write(name, comment, frames, extra=()):
    rows = len(frames)
    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="140" height="{rows * 110}" viewBox="0 0 140 {rows * 110}">',
        f"  <!-- {comment}",
        "       Generated by tools/plasma-frames.py – edit that, not this file. -->",
        *extra,
    ]
    for i, args in enumerate(frames):
        lines += frame(*args[:1], i * 110, *args[1:])
    lines.append("</svg>")
    path = THEME / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    print("wrote", path)


# Text fields (search in AppGrid, KRunner, network passwords …): dark, thin frame,
# blue frame on focus. Hover/focus are drawn on top of the base.
write(
    "widgets/lineedit.svg",
    "Square GOBLINCAKES text field: dark with a thin frame, blue when focused.",
    [
        ("base", BORDER, NIGHT, 1, 6),
        ("hover", PANEL_BORDER, NONE, 1, 0),
        ("focus", ACCENT, NONE, 1, 0),
        ("focusframe", ACCENT, NONE, 1, 1),
    ],
    extra=['  <rect id="hint-focus-over-base" x="130" y="0" width="1" height="1" fill="none"/>'],
)

# Buttons. "toolbutton-*" are the flat buttons (only visible on hover/press).
write(
    "widgets/button.svg",
    "Square, flat GOBLINCAKES buttons.",
    [
        ("normal", BORDER, DEEP, 1, 6),
        ("hover", ACCENT, NONE, 1, 6),
        ("pressed", ACCENT, ACCENT, 1, 6),
        ("focus", ACCENT, NONE, 1, 6),
        ("toolbutton-hover", PANEL_BORDER, SUBTLE, 1, 6),
        ("toolbutton-pressed", ACCENT, ACCENT, 1, 6),
        ("toolbutton-focus", ACCENT, NONE, 1, 6),
    ],
)

# Highlights in lists and grids (search results, menus, AppGrid).
write(
    "widgets/viewitem.svg",
    "Square GOBLINCAKES highlights: accent blue, see-through.",
    [
        ("normal", ACCENT, NONE, 1, 4, 0.0),
        ("hover", ACCENT, ACCENT, 1, 4, 0.6, 0.18),
        ("selected", ACCENT, ACCENT, 1, 4, 0.9, 0.35),
        ("selected+hover", ACCENT, ACCENT, 1, 4, 1.0, 0.45),
    ],
)

# Task manager (open programs in the dock and the top bar): square, flat. The active
# program a darker blue than the accent (the user found Breeze's accent too bright),
# other running programs a dim tile, minimised ones only a frame.
TASK_ACTIVE = "#1B3A78"
TASK_ATTENTION = "#D9822B"
write(
    "widgets/tasks.svg",
    "Square GOBLINCAKES task buttons: active = dark blue, running = dim tile.",
    [
        ("normal", SUBTLE, SUBTLE, 1, 2),
        ("hover", PANEL_BORDER, PANEL_BORDER, 1, 2),
        ("focus", ACCENT, TASK_ACTIVE, 1, 2),
        ("minimized", SUBTLE, NONE, 1, 2),
        ("attention", TASK_ATTENTION, TASK_ATTENTION, 1, 2, 1.0, 0.35),
    ],
)

# Tooltips: same as popups, no shadow.
write(
    "widgets/tooltip.svg",
    "Square GOBLINCAKES tooltip, same look as popups (dialogs/background.svg).",
    [("", BORDER, NIGHT, 1, 6)],
)
